# General Config
baseIncomeTime: 5

# Jobs
Jobs:
  Miner:
    group: Civilian
    playerLimit: 5
    tasks: [Mine Stone]
    baseIncome: 10
    baseXp: 5
    minLvl: 0
    electionRequired: false
    permissionRequired: false
    icon: IRON_PICKAXE

  Police Man:
    group: Government
    playerLimit: 5
    tasks: [Capture Criminal]
    baseIncome: 15
    baseXp: 10
    minLvl: 0
    electionRequired: false
    permissionRequired: false
    icon: STONE_SWORD

  Police Officer:
    group: Government
    playerLimit: 2
    tasks: [Capture Criminal]
    baseIncome: 20
    baseXp: 15
    minLvl: 5
    electionRequired: false
    permissionRequired: false
    icon: IRON_SWORD

  Police Major:
    group: Government
    playerLimit: 1
    tasks: [Capture Criminal]
    baseIncome: 25
    baseXp: 20
    minLvl: 10
    electionRequired: false
    permissionRequired: false
    icon: DIAMOND_SWORD

  Drug Dealer:
    group: Criminal
    playerLimit: 5
    tasks: [Brew Drugs]
    baseIncome: 5
    baseXp: 5
    minLvl: 0
    electionRequired: false
    permissionRequired: false
    icon: POTION

  Bank Robber:
    group: Criminal
    playerLimit: 5
    tasks: [Rob the Bank]
    baseIncome: 5
    baseXp: 10
    minLvl: 5
    electionRequired: false
    permissionRequired: false
    icon: TNT

# Groups
Groups:
  Civilian:
    maxLvl: 10
    friendlyFire: true
    canBeCriminal: true

  Government:
    maxLvl: 10
    friendlyFire: false
    canBeCriminal: false

  Criminal:
    maxLvl: 10
    friendlyFire: true
    canBeCriminal: true

# Tasks
Tasks:
  Mine Stone:
    income: 10
    xp: 10
    actions: [mineStone]
    description: "Mine 15 stone"

  Capture Criminal:
    income: 10
    xp: 10
    actions: [ DEBUG ]
    description: "Capture Criminals"

  Brew Drugs:
    income: 10
    xp: 10
    actions: [ DEBUG ]
    description: "Brew some drugs"

  Rob the Bank:
    income: 10
    xp: 10
    actions: [ DEBUG ]
    description: "Rob the local bank"

Actions:
  chop_25:
    name: Chop Wood
    description: Chop 25 wood
    type: ChopWood
    number: 25
  craft_sticks:
    name: STICKSSSS
    description: Craft 25 sticks
    type: CraftItem
    number: 25
    itemType: STICK
  fish:
    name: Go Fishing
    description: Fish 25 fish
    number: 25
  mineIron:
    name: Mine Iron
    description: Mine 25 iron
    type: MineBlock
    number: 25
    blockType: IRON_ORE
  mineStone:
    name: Mine 15 Stone
    description: Mine 15 stone
    type: MineBlock
    number: 15
    blockType: STONE