depend: [Vault, RecraftedCore]
api-version: 1.16
commands:
  jobs:
    description: Show all available commands
    usage: /jobs
    permission: drp.job
    permission-message: You don't have the basic permissions for jobs
  tasks:
    description: Show all tasks for your current job
    usage: /tasks
    permission: drp.tasks
    permission-message: You don't have the basic permissions for tasks
  elections:
    description: Show all elections that are currently going on
    usage: /elections
    permission: drp.vote
    permission-message: You don't have the permission to vote

permissions:
  drp.*:
    description: Access ALL DarkRp commands
    default: false
    children:
      drp.job.*: true
      drp.tasks.*: true

  drp.job:
    description: Access all basic job commands
    default: true

  drp.tasks:
    description: Access all basic task commands
    default: true

  drp.job.*:
    description: Join all jobs, where a permission is required
    default: false

  drp.vote:
    description: Show all elections and vote for a candidate
    default: true
