depend: [Vault, RecraftedCore, PlaceholderAPI]
api-version: 1.16
commands:
  jobs:
    description: Show all available commands
    usage: /jobs
    permission: drp.job
    permission-message: You don't have the basic permissions for jobs
  tasks:
    description: Show all tasks for your current job
    usage: /tasks
    permission: drp.tasks
    permission-message: You don't have the basic permissions for tasks
  elections:
    description: Show all elections that are currently going on
    usage: /elections
    permission: drp.vote
    permission-message: You don't have the permission to vote
  createLaw:
    description: Create a new law
    usage: /createLaw <law name> <Description>
    permission: drp.laws.create
    permission-message: You don't have the permission to create laws
  removeLaw:
    description: Delete an existing law
    usage: /removeLaw <law name>
    permission: drp.laws.remove
    permission-message: You don't have the permissions to remove laws
  laws:
    description: Show all laws
    usage: /laws
    permission: drp.laws.show
    permission-message: You don't have the permissions to see the laws
  setTaxes:
    description: Set the tax amount
    usage: /setTaxes <amount>
    permission: drp.laws.taxes
    permission-message: You don't have the permissions to set the taxes
  demote:
    description: Demote another player from his job
    usage: /demote <playername>

permissions:
  drp.*:
    description: Access ALL DarkRp commands
    default: false
    children:
      drp.job.*: true
      drp.tasks.*: true

  drp.job:
    description: Access all basic job commands
    default: true

  drp.tasks:
    description: Access all basic task commands
    default: true

  drp.job.*:
    description: Join all jobs, where a permission is required
    default: false

  drp.vote:
    description: Show all elections and vote for a candidate
    default: true

  drp.laws.taxes:
    description: Set taxes when in a job that is taged with major
    default: true

  drp.laws.create:
    description: Makes it possible to create a new law when in a job taged with major
    default: true

  drp.laws.remove:
    description: Makes it possible to remove an existing law when in a job taged with major
    default: true

  drp.laws.show:
    description: Makes it possible to see all laws that are currently available
    default: true
